// Auto generated by Java Poet
package com.example.demo.controller;

import com.example.demo.model.SchoolResponse;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import java.lang.String;
import java.lang.SuppressWarnings;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Api(
    value = "api/market_place",
    description = "School profile",
    produces = "application/json"
)
@RequestMapping("api/market_place")
@SuppressWarnings("unchecked")
public class SchoolController {
  @ApiOperation(
      value = "get user",
      response = SchoolResponse.class
  )
  @ApiResponses({
      @ApiResponse(code = 200, message = "user Details Retrieved", response = SchoolResponse.class),
      @ApiResponse(code = 500, message = "Internal Server Error"),
      @ApiResponse(code = 404, message = "user not found")
  })
  @GetMapping("user")
  public ResponseEntity<SchoolResponse> getAPI(@RequestParam("id") String id,
      @RequestParam("key") String key) {
    // TODO
    return null;
  }
}
