package com.example.demo.baseService;

import com.fasterxml.classmate.types.TypePlaceHolder;
import com.squareup.javapoet.*;
import com.sun.deploy.ui.AppInfo;
import org.springframework.context.annotation.Bean;
import org.springframework.http.ResponseEntity;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import javax.lang.model.element.Modifier;
import javax.security.auth.login.Configuration;
import springfox.documentation.spring.web.plugins.Docket;

import java.io.IOException;
import java.nio.file.Paths;

public class SwaggerBuilderService {

    public void swaggerGenerator(){
//        System.out.println(DocumentationType.SWAGGER_2);

//        MethodSpec apiInfo = MethodSpec.methodBuilder("apiInfo")
//                .addModifiers(Modifier.PRIVATE)
//                .returns(AppInfo.class)
//
//                .addCode("return new ApiInfoBuilder()\n"
//                        + ".title(\"Customer Management Rest APIs\")\n"
//                        + ".description(\"This page lists all the rest apis for Customer Manage App.\")\n"
//                        + "  .version(\"1.0-SNAPSHOT\")\n"
//                )
//                .build();


        Class<?> act = Object.class;

        try {
            act = Class.forName("DocumentationType.SWAGGER_2");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

        System.out.println(DocumentationType.SWAGGER_2.getClass());
        System.out.println(act);


        MethodSpec produceApi = MethodSpec.methodBuilder("produceApi")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Bean.class)
                .returns(Docket.class)
                .addStatement("return new Docket $T",act)
//                .addStatement(".apiInfo($T)", apiInfo)
//                .addStatement(".select()")
//                .addStatement(".apis($T)", RequestHandlerSelectors.basePackage("com.example.demo"))
//                .addCode(
//                        ".paths(paths())\n"+
//                                ".build()"
//                )
                .build();



        TypeSpec controllerSpec = TypeSpec.classBuilder("SwaggerConfig" )
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Configuration.class)
                .addAnnotation(EnableSwagger2.class)

                .addMethod(produceApi)
                .build();

        JavaFile controllerJavafile = JavaFile.builder("com.example.demo.config",controllerSpec)
                .addFileComment("Auto generated by Java Poet")
                .build();


        try {
            controllerJavafile.writeTo(Paths.get("src/main/java"));

        }catch (IOException e) {
            // TODO: handle exception
            System.out.println("fail !!!");
        }



    }




}
