// Auto generated by Java Poet
package com.example.demo.config;

import java.lang.Object;
import javax.security.auth.login.Configuration;
import org.springframework.context.annotation.Bean;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfig {
  @Bean
  public Docket produceApi() {
    return new Docket Object;
  }
}
