// Auto generated by Java Poet
package com.example.demo.model;

import java.lang.String;

public class PhoneNumber {
  private String number;

  private String type;

  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }
}
